FROM maven:3.5.3-jdk-8-alpine

# copy src files
COPY src /code/src

# copy pom.xml
COPY pom.xml /code

# copy testng.xml file
COPY testng.xml /code

# Running command
RUN mvn -f /code/pom.xml clean test -DskipTests=true
#RUN mvn -f /code/pom.xml test -DBROWSER=$BROWSER -DHUB_HOST=$HUB_HOST